[package]
name = "zsw-egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
egui = { version = "0.19.0", features = ["default_fonts"] }
egui_wgpu_backend = "0.20.0"
egui_winit_platform = "0.16.0"
epi = "0.17"
tokio = "1.26.0"
tracing = "0.1.37"
winit = "0.27.5"
zsw-error = { version = "0.1.0", path = "../zsw-error" }
zsw-wgpu = { version = "0.1.0", path = "../zsw-wgpu" }
