[package]
name    = "zsw-egui"
version = "0.1.0"
edition = "2024"

[dependencies]

# Workspace
zsw-wayland = { workspace = true }
zsw-wgpu    = { workspace = true }

derive_more            = { features = ["full"], workspace = true }
egui                   = { features = ["default_fonts"], workspace = true }
egui-wgpu              = { workspace = true }
euclid                 = { workspace = true }
smithay-client-toolkit = { workspace = true }
tracing                = { workspace = true }
wgpu                   = { workspace = true }
xkeysym                = { workspace = true }

[lints]
workspace = true
