[workspace]

members = ["zsw", "zsw-util", "zsw-wgpu", "zsw-error", "zsw-egui"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.70"
async-channel = "1.8.0"
async-once-cell = "0.4.4"
async-walkdir = "0.2.0"
bytemuck = { version = "1.13.1", features = ["derive"] }
cgmath = "0.18.0"
clap = { version = "4.1.11", features = ["derive"] }
console-subscriber = "0.1.8"
crossbeam = "0.8.2"
dashmap = "5.4.0"
directories = "4.0.1"
duplicate = "0.4.1"
egui = { version = "0.19.0", features = ["default_fonts"] }
egui_wgpu_backend = "0.20.0"
egui_winit_platform = "0.16.0"
epi = "0.17.0"
extend = "1.2.0"
futures = "0.3.27"
image = "0.24.5"
include_dir = "0.7.3"
itertools = "0.10.5"
num-rational = "0.4.1"
opener = "0.5.2"
rand = "0.8.5"
rayon = "1.7.0"
sealed = "0.4.0"
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
serde_with = "2.3.1"
serde_yaml = "0.9.19"
thiserror = "1.0.40"
tokio = { version = "1.26.0", features = ["full", "tracing"] }
tokio-stream = { version = "0.1.12", features = ["fs"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
wgpu = "0.14.2"
winit = "0.27.5"


# Compile `image` (and some it's dependencies, which actually load images) in release mode,
# else it's too slow to meaningfully test other features
[profile.dev.package.image]
opt-level = 3
[profile.dev.package.png]
opt-level = 3
[profile.dev.package.jpeg-decoder]
opt-level = 3

# Add debug to release for profiling
[profile.release]
debug = true
