[workspace]

members = ["zsw", "zsw-playlist", "zsw-img", "zsw-wgpu", "zsw-egui", "zsw-panels", "zsw-profiles", "zsw-util", "zsw-side-effect-macros"]
resolver = "2"

# Compile `image` in release mode, else it's too slow to meaningfully
# test other features
[profile.dev.package.image]
opt-level = 3

# Add debug to release for profiling
[profile.release]
debug = true
