[package]
edition = "2021"
name = "zsw"
resolver = "2"
version = "0.1.0"

[dependencies]

# Windowing
winit = "0.26.1"

# Rendering
wgpu = {version = "0.12.0", features = ["serde", "replay"]}

# Async
pollster = "0.2.4"

# X11
x11 = {version = "2.18.2", features = ["xlib"]}

# Serialization
serde = {version = "1.0.132", features = ["derive"]}
serde_json = "1.0.73"

# Math
cgmath = "0.18.0"

# Image
image = "0.23.14"

# Random
rand = "0.8.4"

# Error handling
anyhow = "1.0.40"
thiserror = "1.0.30"

# Logging
log = "0.4.14"
simplelog = "0.11.2"

# Cmd
clap = "3.0.7"

# Util
bytemuck = {version = "1.7.3", features = ["derive"]}
#num-rational = "0.4.0"

# Filesystem
notify = "4.0.17"

# Threads
crossbeam = "0.8.1"
parking_lot = "0.11.2"

# Hashing
twox-hash = "1.6.1"

# Compile all dependencies in release mode, or else it's too slow to
# meaningfully tests most things
[profile.dev.package."*"]
opt-level = 3

# Add debug to release for profiling
[profile.release]
debug = true
