absolute-paths-allowed-crates = [
	# `tokio` mirrors a lot of `std`'s api, so we want to explicitly mention when
	# using `tokio`,
	"tokio",

	# `tracing_subscriber::fmt` makes this ambiguous with `std::fmt`
	"tracing_subscriber",

	# Crate consists of only nondescript modules
	"naga_oil",
]
