disallowed-methods = [
  {path = "crossbeam::channel::Receiver::recv", reason = "Might block"},
  {path = "crossbeam::channel::Sender::send", reason = "Might block"},
  {path = "lock_api::Mutex::lock", reason = "Might block"}, # Note: Technically should be `parking_lot`'s, but lint doesn't work with type alias
]
