tokio_worker_threads = 2
rayon_worker_threads = 2
log_file = "latest.log"
# upscale_cache_dir = "/path/to/cache"
# upscale_cmd = "/upscale/cmd"
# upscale_exclude = ["/path/to/exclude"]

[[default.panels]]
panel = "multiple.toml"
playlist = "example1"

[[default.panels]]
panel = "quarter.toml"
playlist = "example1"

#[[default.panels]]
#panel = "full.toml"
#playlist = "example1"
