tokio_worker_threads = 2
rayon_worker_threads = 2
log_file             = "latest.log"
# upscale_cache_dir = "/path/to/cache"
# upscale_cmd = "/upscale/cmd"
# upscale_exclude = ["/path/to/exclude"]

[[default.panels]]
panel    = "multiple"
playlist = "example1"


[[default.panels]]
panel    = "quarter"
playlist = "example1"


#[[default.panels]]
#panel = "full"
#playlist = "example1"

#[[default.panels]]
#panel = "cross-screen"
#playlist = "example1"
