tokio_worker_threads: 2
rayon_worker_threads: 2
log_file: latest.log
shaders_dir: shaders/
upscale_cache_dir: null # Use default
upscale_cmd: null # None
upscale_exclude: [] # None
default_panel_group: panels/example1.yaml
