warn = [
  "clippy::pedantic",
  "clippy::nursery",
]

deny = [
  # Must use `expect` instead of unwrap
  "clippy::unwrap_used", #
  # Shouldn't panic, unless really needed
  "clippy::panic",
  "clippy::expect_used", #
  # Must use `unsafe` in `unsafe fn`
  "unsafe_op_in_unsafe_fn",
]

allow = [
  ## Style
  "clippy::implicit_return",
  "clippy::multiple_inherent_impl",
  "clippy::pattern_type_mismatch",
  "clippy::wildcard_enum_match_arm",
  "clippy::match_wildcard_for_single_variants",
  "clippy::match_bool",
  "clippy::single_match_else",
  "clippy::if_not_else",
  "clippy::shadow_reuse",
  "clippy::shadow_same",
  "clippy::else_if_without_else",
  "clippy::self_named_module_files",
  "clippy::items_after_statements",
  "clippy::module_name_repetitions", #
  ## Performance
  # The compiler should transform the code into that, not us
  "clippy::suboptimal_flops",
]
