warn = [
  "clippy::pedantic",
  "clippy::nursery",
]

deny = [
  # Must use `expect` instead of unwrap
  "clippy::unwrap_used", #
  # Must use `unsafe` in `unsafe fn`
  "unsafe_op_in_unsafe_fn",
]

allow = [
  ## Style
  "clippy::implicit_return",
  "clippy::multiple_inherent_impl",
  "clippy::pattern_type_mismatch",
  "clippy::wildcard_enum_match_arm",
  "clippy::match_wildcard_for_single_variants",
  "clippy::match_bool",
  "clippy::single_match_else",
  "clippy::single_match",
  "clippy::if_not_else",
  "clippy::shadow_reuse",
  "clippy::shadow_same",
  "clippy::else_if_without_else",
  "clippy::self_named_module_files",
  "clippy::items_after_statements",
  "clippy::module_name_repetitions", #
  ## Performance
  # The compiler should transform the code into that, not us
  "clippy::suboptimal_flops", #
  ## Others
  "clippy::missing_errors_doc", # TODO: Remove
  "clippy::missing_panics_doc", # Most panics are internal assertions
  "clippy::unnecessary_wraps", # Might fail in the future
]
