[package]
name    = "zsw-wgpu"
version = "0.1.0"
edition = "2024"

[dependencies]
app-error = { workspace = true }
tokio     = { workspace = true }
tracing   = { workspace = true }
wgpu      = { workspace = true }
winit     = { workspace = true }

[lints]
workspace = true
