[package]
name = "zsw"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-channel = { workspace = true }
async-once-cell = { workspace = true }
async-walkdir = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
cgmath = { workspace = true }
clap = { workspace = true, features = ["derive"] }
console-subscriber = { workspace = true, optional = true }
crossbeam = { workspace = true }
dashmap = { workspace = true }
directories = { workspace = true }
egui = { workspace = true, features = ["default_fonts"] }
epi = { workspace = true }
extend = { workspace = true }
futures = { workspace = true }
image = { workspace = true }
include_dir = { workspace = true, optional = true }
itertools = { workspace = true }
num-rational = { workspace = true }
opener = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
sealed = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true, features = ["full", "tracing"] }
tokio-stream = { workspace = true, features = ["fs"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
wgpu = { workspace = true }
winit = { workspace = true }
zsw-error = { path = "../zsw-error" }
zsw-util = { path = "../zsw-util" }
zsw-wgpu = { path = "../zsw-wgpu" }
zsw-egui = { path = "../zsw-egui" }

[features]

default = ["include-shaders"]
tokio-console = ["dep:console-subscriber"]
include-shaders = ["dep:include_dir"]
locker-validation = []
