[package]
name = "zsw"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
cgmath = { workspace = true }
clap = { workspace = true, features = ["derive"] }
console-subscriber = { workspace = true, optional = true }
crossbeam = { workspace = true }
directories = { workspace = true }
egui = { workspace = true, features = ["default_fonts"] }
futures = { workspace = true }
image = { workspace = true }
itertools = { workspace = true }
num-rational = { workspace = true }
opener = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true }
tokio = { workspace = true, features = ["full", "tracing"] }
tokio-stream = { workspace = true, features = ["fs"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
wgpu = { workspace = true }
winit = { workspace = true, features = ["x11"] }
rfd = { workspace = true }
zsw-util = { path = "../zsw-util" }
zsw-wgpu = { path = "../zsw-wgpu" }
zsw-egui = { path = "../zsw-egui" }
zutil-app-error = { workspace = true }

[features]

tokio-console = ["dep:console-subscriber"]
locker-validation = []

[lints]
workspace = true
