[package]
edition = "2021"
name = "zsw"
resolver = "2"
version = "0.1.0"

[dependencies]

# Zsw
zsw-side-effect-macros = {path = "../zsw-side-effect-macros"}

# Windowing
winit = "0.26.1"

# Rendering
wgpu = {version = "0.12.0", features = ["serde", "replay"]}

# Gui
egui = "0.16.1"
egui_wgpu_backend = "0.16.0"
egui_winit_platform = "0.13.0"
epi = "0.16.0"

# Async
async-channel = "1.6.1"
async-lock = "2.4.0"
pollster = "0.2.4"

# X11
x11 = {version = "2.18.2", features = ["xlib"]}

# Serialization
serde = {version = "1.0.132", features = ["derive"]}
serde_json = "1.0.73"

# Math
cgmath = {version = "0.18.0", features = ["serde"]}

# Image
image = "0.23.14"

# Random
rand = "0.8.4"

# Error handling
anyhow = "1.0.52"
thiserror = "1.0.30"

# Logging
chrono = "0.4.19"
fern = {version = "0.6", features = ["colored"]}
log = "0.4.14"

# Cmd
clap = "3.0.7"

# Util
bytemuck = {version = "1.7.3", features = ["derive"]}
#num-rational = "0.4.0"

# Filesystem
# TODO: Use `notify` once issues with it using `std`'s `mpsc` are fixed
#notify = "4.0.17"
native-dialog = "0.6.3"

# Threads
crossbeam = "0.8.1"
parking_lot = {version = "0.11.2", features = ["deadlock_detection"]}

# Hashing
twox-hash = "1.6.1"
