[package]
edition = "2021"
name = "zsw"
resolver = "2"
version = "0.1.0"

[dependencies]

# Zsw
zsw-egui = {path = "../zsw-egui"}
zsw-img = {path = "../zsw-img"}
zsw-panels = {path = "../zsw-panels"}
zsw-playlist = {path = "../zsw-playlist"}
zsw-profiles = {path = "../zsw-profiles"}
zsw-renderer = {path = "../zsw-renderer"}
zsw-settings-window = {path = "../zsw-settings-window"}
zsw-side-effect-macros = {path = "../zsw-side-effect-macros"}
zsw-util = {path = "../zsw-util"}
zsw-wgpu = {path = "../zsw-wgpu"}

# Windowing
winit = "0.26.1"

# Rendering
wgpu = {version = "0.12.0", features = ["serde", "replay"]}

# Gui
egui = "0.16.1"
egui_wgpu_backend = "0.16.0"
egui_winit_platform = "0.13.0"
epi = "0.16.0"

# Async
async-channel = "1.6.1"
futures = "0.3.21"
pollster = "0.2.4"

# Serialization
serde = {version = "1.0.132", features = ["derive"]}
serde_json = "1.0.73"

# Math
cgmath = {version = "0.18.0", features = ["serde"]}

# Image
image = "0.23.14"

# Random
rand = "0.8.4"

# Error handling
anyhow = "1.0.52"
thiserror = "1.0.30"

# Logging
chrono = "0.4.19"
fern = {version = "0.6.0", features = ["colored"]}
log = "0.4.14"

# Cmd
clap = {version = "3.0.7", features = ["derive"]}

# Util
bytemuck = {version = "1.7.3", features = ["derive"]}
#num-rational = "0.4.0"

# Filesystem
# TODO: Use `notify` once issues with it using `std`'s `mpsc` are fixed
#notify = "4.0.17"
native-dialog = "0.6.3"

# Threads
crossbeam = "0.8.1"
parking_lot = {version = "0.12.0", features = ["deadlock_detection"]}
rayon = "1.5.1"
