[[panels]]
display = "multiple"

[panels.shader]
type          = "fade"
playlists     = ["example1"]
duration      = 5.0
fade_duration = 1.0
fade          = "out"
strength      = 1.0


[[panels]]
display = "quarter"

[panels.shader]
type          = "fade"
playlists     = ["example1"]
duration      = 5.0
fade_duration = 1.0
fade          = "white"
strength      = 1.0
