[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }

[[panels]]
display = "quarter"
shader  = { type = "none" }
