[package]
edition = "2021"
name = "zsw-side-effect-macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]

# Macro
proc-macro-error = "1.0.4"
quote = "1.0.15"
syn = {version = "1.0.86", features = ["full", "extra-traits"]}
