[package]
edition = "2021"
name = "zsw-util"
version = "0.1.0"

[dependencies]

# Zsw

# Image
image = { workspace = true }

# Async
futures = { workspace = true }
tokio = { workspace = true }

# Math
cgmath = { workspace = true, features = ["serde"] }

# Util
duplicate = { workspace = true }
itertools = { workspace = true }
extend = { workspace = true }

# Error
anyhow = { workspace = true }

# Serde
serde = { workspace = true }
serde_json = { workspace = true }

# Logging
tracing = { workspace = true }

[lints]
workspace = true
