[package]
edition = "2021"
name = "zsw-util"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Zsw

# Image
image = "0.24.5"

# Async
futures = "0.3.25"

# Math
cgmath = { version = "0.18.0", features = ["serde"] }

# Util
duplicate = "0.4.1"

# Error
anyhow = "1.0.66"

# Serde
serde = "1.0.147"
serde_json = "1.0.88"

# Logging
tracing = "0.1.37"

# Threads
crossbeam = "0.8.2"
parking_lot = "0.12.1"
