[package]
edition = "2024"
name    = "zsw-util"
version = "0.1.0"

[dependencies]
app-error    = { workspace = true }
duplicate    = { workspace = true }
euclid       = { features = ["serde"], workspace = true }
extend       = { workspace = true }
image        = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
toml         = { workspace = true }
tracing      = { workspace = true }
zutil-cloned = { workspace = true }

[lints]
workspace = true
